[build]
  command = "npm run build"       # Build command for Next.js
  publish = ".next"               # Next.js build output directory
  functions = ".netlify/functions" # Functions directory for serverless functions

[functions]
  included_files = ["./sanity/**"] # Ensure Sanity files are included in the build

[images]
  remote_images = [
    "^(?:http(?:s)?:\\/\\/s3-alpha-sig\\.figma\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
    "^(?:http(?:s)?:\\/\\/cdn\\.sanity\\.io(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
  ]

[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

[[redirects]]
  from = "/_ipx/*"
  to = "/.netlify/images?url=:url&w=:width&q=:quality"
  status = 200

  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

[context.production]
  [context.production.images]
    remote_images = [
      "^(?:http(?:s)?:\\/\\/s3-alpha-sig\\.figma\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/cdn\\.sanity\\.io(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]

[context.main]
  [context.main.images]
    remote_images = [
      "^(?:http(?:s)?:\\/\\/s3-alpha-sig\\.figma\\.com(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$",
      "^(?:http(?:s)?:\\/\\/cdn\\.sanity\\.io(?:\\/(?!\\.)(?:(?:(?!(?:^|\\/)\\.).)*?)|$))$"
    ]
